### ISSUE TITLE
Mi Browser Permission Problem

### ISSUE THREAD

**Issue by ahmetozalp** [peer-calls/peer-calls#100]
**Describe the bug**

**Bug Report Checklist**

- [] I have granted camera/microphone access permissions while testing
- [+] This bug is reproducible on https://peercalls.com

**To Reproduce**
1. Go to 'mi browser'
2. Click on 'peercalls'
3. See error

**Expected behavior**

**Screenshots**

Video: https://www.youtube.com/watch?v=pJtt8wPBi54&feature=youtu.be

**Comment by jeremija** [comment]
What are the results when you open this page: https://test.webrtc.org/ ?
