### ISSUE TITLE
Reconnection

### ISSUE THREAD

**Issue by ahmetozalp** [peer-calls/peer-calls#101]
Hello, I noticed something at peercalls.com. The connection has a black screen user renewal reconnecting. During the broadcast, I think my codes are a bit old.

where are you doing this I update my codes

**Comment by jeremija** [comment]
Hi @ahmetozalp. Could provide steps to reproduce? Or could you record a video so I can see what's going on? Thanks!

**Comment by ahmetozalp** [comment]
I'll send it as soon as possible
