### ISSUE TITLE
Node Backend

### ISSUE THREAD

**Issue by ahmetozalp** [peer-calls/peer-calls#106]
Why was the nodejs backend server development stopped? I see it stopped in v3.

**Comment by ahmetozalp** [comment]
hellooo?

**Comment by jeremija** [comment]
@ahmetozalp I'd like to remind you that **all development of Peer Calls is done in my free time**. Therefore, I will respond to issues whenever I have free time, unless you are a paying customer. I try to help as best as I can, when I can.

Also, the answer to your question is in the [README](https://github.com/peer-calls/peer-calls/blob/master/README.md). The master branch contains an implementation of a Selective Forwarding Unit, which should make it a better experience for more users in a room once it's stable, and implementing this in NodeJS would have been much harder than in Go. The source code of version 3 is still available in the `version-3` branch.

**Comment by ahmetozalp** [comment]
thank you. give me email address?

**Comment by jeremija** [comment]
My contact e-mail is also in the readme :)
