### ISSUE TITLE
Socket issue on server

### ISSUE THREAD

**Issue by Sameer-hesta** [peer-calls/peer-calls#113]
**Socket connection error**
WebSocket connection to 'wss://demovideo.my-domain.com/ws/123/za80HWiFPN4H4LGAHyIAc7' failed: Error during WebSocket handshake: Unexpected response code: 426

**Comment by jeremija** [comment]
Thanks for the bug report! Are you are running PeerCalls v4 (master branch) or v4? Can you reproduce this bug on https://peercalls.com/alpha ? if you're running v4?

**Comment by Sameer-hesta** [comment]
Actually I have set up this on ubuntu by git. I install node v8.17.0 and go go1.14.2. When I try to run this on the development by the command `npm run start:watch` I get the following error  
[            **wss] Error accepting websocket connection: failed to accept WebSocket connection: WebSocket protocol violation: Connection header "Keep-Alive" does not contain Upgrade**


And on the browser, I am getting following error on the console 

WebSocket  failed: Error during WebSocket handshake: Unexpected response code: 426


I am using https Help will we appreciated

**Comment by jeremija** [comment]
Are you running Peer Calls behind a proxy server?

**Comment by Sameer-hesta** [comment]
> Are you running Peer Calls behind a proxy server?

Yes

**Comment by jeremija** [comment]
You need to ensure your proxy is configured to support websocket connections for Peer Calls.

I'm using nginx, and it has these settings:

```
        proxy_set_header Upgrade                          $http_upgrade;
         proxy_set_header Connection                       "upgrade";
```

You need to find an equivalent for Apache, possibly the [wstunnel](https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html) module

**Comment by Sameer-hesta** [comment]
Thank you but already enabled proxy_wstuneel

**Comment by jeremija** [comment]
Do you have HTTP 2 enabled?

**Comment by Sameer-hesta** [comment]
Yes

**Comment by jeremija** [comment]
Can you try disabling it for `/ws` path? There's an issue with a websocket library (or Golang) with websockets and HTTP2: https://github.com/nhooyr/websocket/issues/4

**Comment by Sameer-hesta** [comment]
Mate thank you for your response 

I have modified apace config for WebSocket


  **RewriteEngine on
  RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
  RewriteCond %{HTTP:CONNECTION} Upgrade$ [NC]
  RewriteRule .* ws://localhost:3000%{REQUEST_URI} [P]**


and thats it

**Comment by jeremija** [comment]
Glad you were able to resolve it!
