### ISSUE TITLE
socket emit

### ISSUE THREAD

**Issue by ahmetozalp** [peer-calls/peer-calls#115]
Hello there,
I want to put socket emit on [this](https://github.com/peer-calls/peer-calls/blob/3ac505e13c2176cc952ddeb45bcc340b8a3d854b/src/client/actions/PeerActions.ts#L100) line, but I could not put it anyway. I still can't get used to the code architecture.

users in the same room

**Comment by jeremija** [comment]
Do you want to send messages and files over websockets instead of a peer connection? Do I understand correctly what you're trying to do?

**Comment by ahmetozalp** [comment]
<img width="793" alt="Ekran Resmi 2020-05-05 13 44 15" src="https://user-images.githubusercontent.com/7665820/81058352-f4d58180-8ed6-11ea-9722-aec64f7a0004.png">
<img width="1019" alt="Ekran Resmi 2020-05-05 13 46 05" src="https://user-images.githubusercontent.com/7665820/81058359-f8690880-8ed6-11ea-8e55-96a49abf9d7d.png">

**Comment by ahmetozalp** [comment]
I want to transfer data from 2nd picture to 1st picture to work in the backend.

**Comment by jeremija** [comment]
Why don't you just use `SocketActions` and send the data via websockets? You can then broadcast to other peers in room on the server side

**Comment by ahmetozalp** [comment]
<img width="1049" alt="Ekran Resmi 2020-05-05 14 39 21" src="https://user-images.githubusercontent.com/7665820/81062226-47ff0280-8ede-11ea-95ed-88c035bcb063.png">


ReferenceError: document is not defined


Do you have any idea how to run this in the backend?

**Comment by jeremija** [comment]
You can't access the document on the backend. Just send a plain object with the necessary information.

**Comment by ahmetozalp** [comment]
thank you.
