### ISSUE TITLE
Network: sfu what is this exactly

### ISSUE THREAD

**Issue by ahmetozalp** [peer-calls/peer-calls#118]
I couldn't find a source in this language in my language. What is SFU exactly? my interviews 2 people maximum SFU is there any use for me?

**Comment by jeremija** [comment]
SFU stands for Selective Forwarding Unit. It is a server component to which users upload their video packets, and then distributes it to other peers. As a result, each peet needs to encode and upload their video only once.

In a mesh network, the peers upload (and potentially encode) their videos to every other peer and this quickly gets expensive.

I'd say if you have a total of 2-3 users you probably have no need for an SFU if you aren't experiencing any issues.

**Comment by ahmetozalp** [comment]
actually some users are alive but i can't find the problem. these problems, when 2 people enter the conference, they see that they are 2 people but there is no communication with the camera and audio and after a while they have connection problem

_private turn server board_

**Comment by jeremija** [comment]
Are you using v3 or v4?

**Comment by ahmetozalp** [comment]
v3 :)

**Comment by jeremija** [comment]
These sort of stability issues are the reason why I started the rewrite to `v4`. I'd be curious to hear if you experience any call quality improvements when using [peercalls.com/beta](https://peercalls.com/beta)? This instance has SFU enabled and I just recently had a conversation with 4 other peers from EU and USA without any issues.

**Comment by ahmetozalp** [comment]
i can't use v4 i don't know golang language

Well, should I pay attention to something about this? how should i recognize the error

**Comment by jeremija** [comment]
You have a few options in v3:

- Check the console logs after setting `localStorage.debug = 'peercalls,simple-peer'` and `localStorage.log = 1`. Make sure to referesh the page after this is set.
- Check the `about:webrtc-internals` in Chrome and `about:webrtc` in Firefox for any error messages.

**Comment by ahmetozalp** [comment]
thanks.
