### ISSUE TITLE
Lag in another peer call with SFU network mode

### ISSUE THREAD

**Issue by vasupal1996** [peer-calls/peer-calls#119]
I tested out a call on sfu network mode. There happens to be lag and jitteriness in the video output of the other peer.
Not Sure Why?

I tested it out by pulling the repo down to my localhost, also tested out at peercalls.com as well. Having the issue in both cases.

**Comment by jeremija** [comment]
Hi @vasupal1996. Thanks for the report. To help me debug this, could you verify the following:

1. Which version of peer calls were you testing? If you don't have a version, a commit ID would help.
2. Were you using peercalls.com, peercalls.com/alpha or peercalls/beta to test?
3. Which browser were you using?
4. How many people were in the call?
5. Could you take a screenshots of Chrome charts for your `RTPOutboundVideoStream` and `RTPInboundVideoStream` on `about:webrtc-internals`. Here are some examples:

![image](https://user-images.githubusercontent.com/1489493/81777383-fc0d1880-94f0-11ea-8f73-f163591544b5.png)



![image](https://user-images.githubusercontent.com/1489493/81777357-f0215680-94f0-11ea-9427-cb80ec4df32c.png)

**Comment by vasupal1996** [comment]
Sure, on my local, I pulled the latest master with the last commit 0f3bb8f2462d01e9f0c33c945f211571bed76399

 and as for chat used https://peercalls.com/beta/
but the issue was in both environments.

I used chrome on my mac (81.0.4044.138) as one peer and android with brave-browser as another, just 2 peers (not tested for more than two peers). 

Here are some screenshots for debugging.
<img width="1440" alt="Screenshot 2020-05-13 at 2 09 03 PM" src="https://user-images.githubusercontent.com/24826141/81791675-a6526380-9524-11ea-8d71-2397e1b3aa1c.png">
<img width="1440" alt="Screenshot 2020-05-13 at 2 09 15 PM" src="https://user-images.githubusercontent.com/24826141/81791717-b23e2580-9524-11ea-8e6c-72528b38d49b.png">


<img width="1440" alt="Screenshot 2020-05-13 at 2 08 45 PM" src="https://user-images.githubusercontent.com/24826141/81791600-8cb11c00-9524-11ea-8674-977fb46aa461.png">

<img width="1440" alt="Screenshot 2020-05-13 at 2 09 24 PM" src="https://user-images.githubusercontent.com/24826141/81791753-c3873200-9524-11ea-89ef-d61b6c630038.png">

**Comment by jeremija** [comment]
Hmm interesting - thanks for sending these! Your packet loss is linearly increasing all the time. Are you testing this on a single or two (multile) devices?

Does it happen when you run the default `NETWORK_TYPE=mesh`?

Also if you run it with `mesh`, it would be great to see if your `packetsLost` chart looks the same. 

If so, it could be due to your network quality. The browsers have better error correction than Peer Calls at the moment since the Jitter Buffer is not implemented.

**Comment by vasupal1996** [comment]
This is on multiple devices Mac and Andriod.

**Comment by vasupal1996** [comment]
These are with MESH

<img width="1440" alt="Screenshot 2020-05-13 at 2 31 26 PM" src="https://user-images.githubusercontent.com/24826141/81793041-75732e00-9526-11ea-988a-e02ae927f89c.png">
<img width="1440" alt="Screenshot 2020-05-13 at 2 31 13 PM" src="https://user-images.githubusercontent.com/24826141/81793058-799f4b80-9526-11ea-931d-f6b7fcf3d1af.png">

**Comment by vasupal1996** [comment]
Could it be the case of latency due to geographic location, cause I'm in India and probably your server is hosted in the US zone?

**Comment by jeremija** [comment]
It could be fore the SFU, but I see that you also have a quite big packet loss on the `mesh` network. Are this last charts from your local Peer Calls instance?

**Comment by vasupal1996** [comment]
Yeah! Well i kinda actually exposed my localhost to internet through tunnelling service ngrok.io which i just now realized is routing the packets to some US server. 

However, when i run it on localhost port in multiple window. It works fine. 

Could it really be the case of geographic location?

**Comment by jeremija** [comment]
Geographic location now makes perfect sense! Ngrok might also throttle your connection, especially if you aren't a paid customer.

If you wish to test on your local network use this command:

```
PEERCALLS_TLS_CERT=./config/cert.example.pem PEERCALLS_TLS_KEY=./config/cert.example.key PEERCALLS_BIND_PORT=8443 PEERCALLS_NETWORK_TYPE=sfu go run main.go
```

And access the app via `https://<your_ip_or_hostname>:8443`

Just make sure to accept the insecure connection on your devices.

**Comment by vasupal1996** [comment]
Thanks

**Comment by ahmetozalp** [comment]
did you fix the problem? @vasupal1996

**Comment by vasupal1996** [comment]
> did you fix the problem? @vasupal1996

Yes! Indeed it was a latency issue due to geographic location. I managed to host the server in my region and was working fine.

**Comment by ahmetozalp** [comment]
You set up my turn server
