### ISSUE TITLE
Screen Not Reload 

### ISSUE THREAD

**Issue by ahmetozalp** [peer-calls/peer-calls#120]
Hello there,

I connected via phone and computer and tried to upload a file from my cell phone, the screen went down on me like in the video, but it did not come again, only sound and black screen but when I look at peercalls.com, this area is constantly renewed, how do you do this? It's just enough for me if I find out how you did it.

Chrome WebRTC Log line:
STUN allocate request timed out.
OR
TURN allocate request timed out.

My Project error video link: https://youtu.be/mn8Ftk1ssJo
Peer Calls video link: https://youtu.be/s3hVOF7IT8k

**Comment by ahmetozalp** [comment]
There is no problem in peercalls.com v3

**Comment by ahmetozalp** [comment]
case STREAM_TRACK_ADD:
      return addStreamTrack(state, action.payload)


not working.

thx.

**Comment by jeremija** [comment]
Hi @ahmetozalp, are you still experiencing the issue? I haven't had the chance to see the video

**Comment by ahmetozalp** [comment]
I live STREAM TRACK ADD does not trigger at all

**Comment by ahmetozalp** [comment]
Proje hatası video bağlantım: https://youtu.be/mn8Ftk1ssJo
Peer Calls video bağlantısı: https://youtu.be/s3hVOF7IT8k

**Comment by jeremija** [comment]
have you tried peercalls.com/beta ?

**Comment by ahmetozalp** [comment]
<img width="948" alt="Ekran Resmi 2020-05-13 14 17 02" src="https://user-images.githubusercontent.com/7665820/81806000-828f1d80-9524-11ea-93d7-f86467688557.png">

**Comment by jeremija** [comment]
Can you reproduce this on https://peercalls.com/beta ?

**Comment by ahmetozalp** [comment]
<img width="907" alt="Ekran Resmi 2020-05-13 14 25 56" src="https://user-images.githubusercontent.com/7665820/81806824-ad2da600-9525-11ea-8867-9df951bb980c.png">

**Comment by ahmetozalp** [comment]
thank you problem fix.

`handleTrack = (track: MediaStreamTrack, stream: MediaStream) => {
    const { user, dispatch } = this
    const userId = user.id
    debug('peer: %s, track', userId)
    // Listen to mute event to know when a track was removed
    // https://github.com/feross/simple-peer/issues/512
    track.onmute = () => {
      debug(
        'peer: %s, track mute (id: %s, stream.id: %s)',
        userId, track.id, stream.id)
      dispatch(StreamActions.removeTrack({
        userId,
        stream,
        track,
      }))
    }

    function addTrack() {
      debug(
        'peer: %s, track unmute (id: %s, stream.id: %s)',
        userId, track.id, stream.id)
      dispatch(StreamActions.addTrack({
        userId,
        stream,
        track,
      }))
    }

    if (!track.muted) {
      addTrack()
    }
    track.onunmute = addTrack`
