### ISSUE TITLE
Clustering in mesh mode

### ISSUE THREAD

**Issue by iesreza** [peer-calls/peer-calls#123]
I tried to have two instances of peer calls in mesh mode and used a common redis to share data between instances.

First i faced a problem: the ws always returns client size 0, i found that the names (metadata) was not written in redis so i put their id instead of their name. i think there are some issue with negotiation.

Then i can see empty boxes of all users but not the live videos. could you write some instructions how to make clusters?

PS:
I found that SetMetadata for redisadapter just reads the data and does not set anything is it right?
```go
func (a *RedisAdapter) SetMetadata(clientID string, metadata string) (ok bool) {
	metadata, err := a.pubRedis.HGet(a.keys.roomClients, clientID).Result()
	a.log.Printf("SetMetadata for clientID: %s, metadata: %s (err: %s)", clientID, metadata, err)
	return err != nil
}
```

Regards

**Comment by jeremija** [comment]
Thanks for pointing this out @iesreza! That was indeed a bug.

I was focusing on the SFU to work, and currently SFU only supports a single node. Once I implement transports for server node-to-node communication, that'll be the time write more tests for redis support.

In the meantime, please let me know if you are stilll experiencing issues with redis when using the mesh network?

**Comment by iesreza** [comment]
You done great job.
Unfortunately i faced some issue when i tried clustering using mesh mode. i can get list of users but not the live video. i think its related to storing data on redis.

For now i accomplished to make cluster in memory mode using path hash load balancing.

**Comment by jeremija** [comment]
Sorry to hear you're still having issues. I'm going to have a deeper look at this over the weekend.

**Comment by jeremija** [comment]
@iesreza This should be fixed now. Please reopen the issue if you continue experiencing problems!
