### ISSUE TITLE
Integration with pion flutter sdk

### ISSUE THREAD

**Issue by iesreza** [peer-calls/peer-calls#124]
Since peer calls uses pion core is it possible to integrate pion flutter sdk?

**Comment by jeremija** [comment]
If you're referring to [ion-flutter-sdk](https://github.com/pion/ion-sdk-flutter), that was built to work with [`pion/ion`](https://github.com/pion/ion/), which is a separate project. Peer Calls currently uses only `pion/webrtc`, which is what `pion/ion` uses under the hood as well.
