### ISSUE TITLE
Adding font

### ISSUE THREAD

**Issue by mrostamii** [peer-calls/peer-calls#125]
As I've seen in the `_variables.sass`, there are two variable

```
$font-sans-serif: "Helvetica Neue", Helvetica, Arial, sans-serif
$font-monospace: Menlo, Monaco, Consolas, "Ubuntu Mono", monospace
```

How to add/install a new font pack to the project?

**Comment by ahmetozalp** [comment]
Hello,

1. Go https://fonts.google.com 
2. Select Font
3. Righ Select this style click
4. Embed tab click
5. Copy 
``` css
@import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap');
```
6. _variables.sass add line.
7. Editing 
``` css
$font-sans-serif: "Montserrat", Helvetica, Arial, sans-serif
```
