### ISSUE TITLE
android front camera not working.

### ISSUE THREAD

**Issue by ahmetozalp** [peer-calls/peer-calls#128]
Hello there,

When I log in from the mobile android phone, there is no problem in the rear camera in the selection of the front and rear cameras, but I get an error when I select the front camera

Error: (NotReadableError: Could not start video source)

** Smartphone (please complete the following information): **
  - Device: Android Vestel
  - OS: 7.0
  - Browser: chrome
  - Version: 83

** Additional context **

![WhatsApp Image 2020-06-11 at 11 06 13](https://user-images.githubusercontent.com/7665820/84361142-e19f8b00-abd3-11ea-8e0b-41c274752ee7.jpeg)
![WhatsApp Image 2020-06-11 at 11 06 14](https://user-images.githubusercontent.com/7665820/84361151-e2d0b800-abd3-11ea-9611-3b6d85d3dc29.jpeg)

**Comment by jeremija** [comment]
Does it work here: https://webrtc.github.io/samples/src/content/devices/input-output/ ?

Also have you tried any other browser on this device?

**Comment by ahmetozalp** [comment]
I tried it now, it works there, but peercalls don't

**Comment by ahmetozalp** [comment]
The error in the screenshot was due to the operation in the camera application on a different tab

But this time I change the camera in the conference. I get this error. I have to stop the previous tracks. Can you take a look at this?

**Comment by jeremija** [comment]
What happens if you select "No video" first, and then the other camera?

**Comment by ahmetozalp** [comment]
running this time

**Comment by ahmetozalp** [comment]
do you have any idea what i can do

**Comment by jeremija** [comment]
I'm not exactly sure since I cannot reproduce this on any of my devices.

My guess is that `stop()` would need to be called on the previously selected `MediaStreamTrack` in `MediaDropdown` component before a new track for the other camera is obtained.

**Comment by ahmetozalp** [comment]
I did research on the internet for a similar error. Previously, the camera says that it gave this error because the camera was not stopped, but I am not sure where to stop it.

**Comment by ahmetozalp** [comment]
Firefox Error Messge: Abort Error Starting video failed.

**Comment by ahmetozalp** [comment]
If you want, you can review the error with free membership on this site.

site: https://live.browserstack.com/
example phone: Xiaomi Redmi Note 7

**Comment by ahmetozalp** [comment]
Hello, is there no way to stop the cameras?

**Comment by jeremija** [comment]
Like I sad in my last post, this is what probably needs to be done:

> My guess is that stop() would need to be called on the previously selected MediaStreamTrack in MediaDropdown component before a new track for the other camera is obtained. But this track is not available in that component at this point.

The problem is that if we `stop()` the track, I'm not sure if we will lose the ability to use `replaceTrack` in the `RTCPeerConnection`. Perhaps that doesn't matter and everything will continue working as it currently is.

So to sum up, a potential fix would pass current local `MediaStreamTrack` to `DeviceDropdown` component, and call `stop()` on it before we request a new track.

Alternatively, we can try to do this automatically in `src/client/reducers/streams.ts` by adding an action like `STOP_LOCAL_VIDEO`  and then dispatching this action in `DeviceDropdown` before a new track is requested:

```
    case 'STOP_LOCAL_VIDEO':
      state.localStreams.camera && state.localStreams.camera.stream.getVideoTracks().forEach(t => t.stop())
      return state
```
