### ISSUE TITLE
Add encryption support using a shared password (Insertable Streams)

### ISSUE THREAD

**Issue by jeremija** [peer-calls/peer-calls#141]

**Comment by chrismgonzalez** [comment]
@jeremija What would it take for e2e encryption to occur on devices using a custom built iOS, MacOS, Windows, or Android app?

**Comment by jeremija** [comment]
Hi @chrismgonzalez, this is experimental technology. Out of all major browsers, I think Chrome is the only one that currently supports it, and it's hidden behind a flag .

I think Electron 9 has support for this as well (since it's based on Chromium), so that should make it easy to build a native Windows/Mac/Linux app. As for iOS and Android, unless if there's a React Native module for this, you'd probably have to use the WebRTC C++ library:

See https://webrtchacks.com/true-end-to-end-encryption-with-webrtc-insertable-streams/:

> This is not a new idea – the webrtc.org library already has a native API for frame encryption. However, this was never exposed to the browser. Surprisingly, it is not used by the current API. This can be seen in channel_send.cc. The difference here is that Insertable Streams needs to be asynchronous.

See [the FrameEncryptor interface](https://source.chromium.org/chromium/chromium/src/+/master:third_party/webrtc/api/crypto/frame_encryptor_interface.h;drc=75f2b243d1ab211ed5a6f380ae76ceb504be8598;l=27).
