### ISSUE TITLE
don't show the video is turned off

### ISSUE THREAD

**Issue by ahmetozalp** [peer-calls/peer-calls#146]
**Describe the feature**

Hello, how can I tell if the user has the camera and microphone turned off. I really need this but I could not find a method.

**Comment by jeremija** [comment]
Unfortunately, I don't think the WebRTC API provides a method for this. The spec even mandates the browsers to send black frames for disabled local video tracks.

You'd have to capture the event when a user changes the audio/video settings and send a message via websockets or data channels to the other participants.
