### ISSUE TITLE
CGO error while building docker image

### ISSUE THREAD

**Issue by dpanyam** [peer-calls/peer-calls#148]
****CGO error while building docker image** **
I am building the peer calls docker image from source on Ubuntu 18.04 with go 1.14 and docker 19 installed on it. I am getting this error while building can someone help me fix this?

**Steps To Reproduce**

1. Git clone the peer-calls repo
2. Introduce a new config.yml at this path  server/config.yml to setup your own ICE servers
3. Install COTURN server as mentioned in README
4. Build docker image 

**Expected behavior**
Expect docker build to pass without errors

**Screenshots**
Added screenshot of the error
<img width="1440" alt="cgo_error" src="https://user-images.githubusercontent.com/11291110/90997621-a9f38d00-e5df-11ea-9c39-9983f370270e.png">

My setup is as follows

- Ubuntu 18.04
- Go version 1.14 ( As mentioned in prerequisite)
- Docker 19.0

**Additional context**

**Comment by jeremija** [comment]
@dpanyam I think this is an issue with Docker on ubuntu and I'm not sure if there's a way I can fix it.

Take a look here: https://github.com/docker/docker-credential-helpers/issues/103#issuecomment-421822269

**Comment by dheerajd3v** [comment]
I discarded the VM having this issue and stood up a new GCE VM  with same versions of docker, go, npm and node. Also i used the same package repo to install docker. Not sure what changed but it worked.

Thanks @jeremija appreciate your response.

**Comment by jeremija** [comment]
Alright, glad you figured it out - I'm going to close this issue then.
