### ISSUE TITLE
Can't enable Jitter Buffer

### ISSUE THREAD

**Issue by Sidefix** [peer-calls/peer-calls#150]
**Describe the bug**
Jitter buffer parameter cannot be enabled from the yml.
There are no clear examples for this anywhere in the documentation, but I have tried every permutation:
- jitter_buffer: true
- jitter-buffer: true
- jitterbuffer: true

And in all instances, the configuration comes up as FALSE on startup log.

**Bug Report Checklist**
- [x] I havexample:anted camera/microphone access permissions while testing
- [N/A] This bug is reproducible on https://peercalls.com
- [N/A] This bug is reproducible on https://peercalls.com/alpha

**Steps To Reproduce**

1. Download peercalls
2. Configure jitter buffer and network type SFU
3. Startup peercalls

**Expected behavior**
Jitter buffer comes up as ENABLED during app startup

**Screenshots**
![image](https://user-images.githubusercontent.com/26040103/91655927-29d89600-eabd-11ea-8fef-82ca6ed61f4b.png)

**Desktop (please complete the following information):**
 - OS:      Ubuntu 20.04
 - Browser  N/A
 - Version  4.0.11

**Additional context**
Issue occurred with 4.0.8 aswell

**Comment by Sidefix** [comment]
Side-note: no other settings from the YML config suffer from this issue; everything else is getting read correctly.

**Comment by jeremija** [comment]
Hi @Sidefix, have you tried this config?

```yaml
network:
  type: 'sfu'
  sfu:
    jitter_buffer: true
```

**Comment by Sidefix** [comment]
![image](https://user-images.githubusercontent.com/26040103/91657098-0fa3b580-eac7-11ea-8704-93e14585d152.png)

Unfortuinately I have tried this exact permutation several times, as stated above. Please see attached screenshot.

**Comment by jeremija** [comment]
Ah, thanks for reporting this bug.  Boolean values would always be set to `false` when there was no corresponding environment variable set. This should be fixed in `v4.0.12`.
