### ISSUE TITLE
chrome 85 cannot access to webcam and microphone

### ISSUE THREAD

**Issue by Archer-Thane** [peer-calls/peer-calls#155]
**Describe the bug**

With no change on code, new chrome update (85) is not able to access to webcam and microphone via standard way of accessing it (with navigator.mediaDevices.getUserMedia). the reported error is: DOMException: Could not start video source.

**Comment by Archer-Thane** [comment]
I also opened a stackoverflow.com question which I tried to explain the problem:
https://stackoverflow.com/questions/63919118/domexception-could-not-start-video-source-chrome-85-update

**Comment by jeremija** [comment]
@Archer-Thane Works fine for me on Chrome for Android 85.

You have left some questions from the bug report template unanswered. Which OS are you using? Can you reproduce this on peercalls.com? If you're on the mobile device, could it be that the app does not have Camera or Microphone permissions?

**Comment by Archer-Thane** [comment]
@jeremija, since I thought that's a chrome bug, I didn't complete the report.
There is an issue submitted on chromium issue tracker which is responsible for this issue.
here is the link:
https://bugs.chromium.org/p/chromium/issues/detail?id=1128913

**Comment by Archer-Thane** [comment]
For those experiencing this issue, just restore chrome to defaults: 
1- open settings
2- on the end of page, click on advanced
3- click on restore to defaults
That's fix the isssue. 
You can close the issue here, since this is not your code problem. Also this will be helpful for those encountering the same problem, since there is a little information about this bug. So as a solution, this can be used.

**Comment by wagesj45** [comment]
@Archer-Thane I'm not entirely sure that's an option. I just  tried running the official Docker image and neither Firefox 80.0.1 or Chrome 85.0.4183.102 were able to load a call. Both received a warning that the browsers were unsupported.

**Comment by jeremija** [comment]
@wagesj45 did you setup TLS? If not you'll only be able to access the cameras from `http://localhost:3000`

**Comment by jeremija** [comment]
Ah I just realized you edited your message. Closing this issue.
