### ISSUE TITLE
Data Storage

### ISSUE THREAD

**Issue by johnuarez** [peer-calls/peer-calls#165]
Hello Team,

is it possible to see wich data is saved from the users in the database?
Thank you for you answers.

Best Regards

John

**Comment by jeremija** [comment]
Hi @johnuarez,

Are you referring to the peercalls.com website or the app itself?

There's no user data saved as there is no persistence. By default Peer Calls uses a `MemoryAdapter` and stores all information about users IDs and their nicknames in memory. This information is deleted after a user leaves the room. Peer Calls can be configured to use a `RedisAdapter`, in which case the same information will be stored in Redis, but it is only used as a distributed cache - this information will be deleted after a user leaves the room.

The only scenario when it won't be deleted from Redis is when Peer Calls app crashes during a call and the handler to remove the information is not invoked.

But this data does not contain any personal identifiable information except the nickname. The user identifier is randomly generated on every page refresh.

Hope this answers your question - let me know if you have more.

**Comment by prologic** [comment]
@jeremija Love you work! ❤️
