### ISSUE TITLE
Remove shared desktop container for localUser (Chrome problem)

### ISSUE THREAD

**Issue by nicksnowww** [peer-calls/peer-calls#166]
**Describe the bug**

While sharing desktop, Chrome's **Stop Sharing** button doesn't remove the video container of the shared screen for `localUser`.
The video container remains but the video is black, the only way to remove the container is to manually stop the sharing from the sharing dropdown menu.

**Bug Report Checklist**

- [x] I have granted camera/microphone access permissions while testing
- [x] This bug is reproducible on https://peercalls.com
- [ ] This bug is reproducible on https://peercalls.com/alpha **(the page is unreachable)**

**Expected behavior**

Clicking **Stop Sharing** should delete the video container for _all_ the users, including `localUser` (aka the person who shared the screen).

---
### Example
**Scenario**: Call between `User 1` and `User 2`

**Step 1**: `User 1` shares his screen

This is what `User 1` sees:

![2020-10-30 12_04_27-Peer Call](https://user-images.githubusercontent.com/64967231/97698634-1770dd80-1aa9-11eb-9060-c9d65420cdd0.png)

This is what `User 2` sees:

![2020-10-30 12_04_40-Peer Call](https://user-images.githubusercontent.com/64967231/97698637-18097400-1aa9-11eb-9bb0-ec7073dd38a2.png)
<br>
<br>
**Step 2**: `User 1` stops sharing the screen with the provided button from Chrome:

![2020-10-30 12_04_59-peercalls com sta condividendo il tuo schermo](https://user-images.githubusercontent.com/64967231/97698638-18a20a80-1aa9-11eb-9126-5e7986ce4323.png)

This is what `User 1` sees now:

![2020-10-30 12_05_09-Peer Call](https://user-images.githubusercontent.com/64967231/97698639-18a20a80-1aa9-11eb-8c68-1ef8a28105d4.png)

And this is what `User 2` sees:

![2020-10-30 12_05_19-Peer Call](https://user-images.githubusercontent.com/64967231/97698640-18a20a80-1aa9-11eb-951f-1b6fc0ed3bba.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser: Chrome
 - Version: 86

**Comment by jeremija** [comment]
Hi @nicksnowww, thanks for a great bug report! You really made it easy for me to track down the problem. I submitted an PR #170 - could you take a look and see if it fixes the issue for you? Thanks!

**Comment by nicksnowww** [comment]
@jeremija thank you very much! Your solution works, I just tested it with your changes :+1:
