### ISSUE TITLE
Volume for call users?

### ISSUE THREAD

**Issue by DillFrescott** [peer-calls/peer-calls#172]
Is there a way to adjust the volume for individual users in the call?

**Comment by jeremija** [comment]
Hello, there's no way to do this in Peer Calls UI currently.

As a workaround you could right click the video and click `Show controls`:

![image](https://user-images.githubusercontent.com/1489493/100497290-af222400-315a-11eb-8978-b98f50f6298f.png)

And then you should be able to use the standard video volume slider to adjust the volume:

![image](https://user-images.githubusercontent.com/1489493/100497298-c3662100-315a-11eb-8605-843fdebad9d5.png)

This was tested in the latest version of Firefox.

**Comment by DillFrescott** [comment]
Thank you for the help.
