### ISSUE TITLE
Using Peer Calls Frontend with Jitsi Meet Backend?

### ISSUE THREAD

**Issue by zeuscronos** [peer-calls/peer-calls#178]
Hello, I'm wondering if is there anyway to use **Peer Calls** Frontend with **Jitsi Meet** Backend?

**Jitsi Meet** backend looks very solid, but in the other hand **Peer Calls** frontend looks way better than **Jitsi Meet** frontend.

Thanks in advance!

**Comment by jeremija** [comment]
Hey, thanks for your interest, but I'm afraid it's not possible to use Jitsi Meet as a backend and there are no plans to add support for this.
