### ISSUE TITLE
Stopping screen sharing by Firefox's native button not handled properly

### ISSUE THREAD

**Issue by yedpodtrzitko** [peer-calls/peer-calls#191]
- When sharing a screen in Firefox, it shows a small bar with "Stop Sharing" button. If this button is used to terminate the screen sharing instead of toggling the "Share Screen" in PeerCalls' toolbar to _off_ state: it does not trigger/propagate any event (`ended`), so the peers don't receive any info the screen stream was terminated. 
- In Firefox that means the last recorded frame of the screen remains in the grid of call participants. In Chrome the screen (last recorded frame) is appearing and disappearing in short intervals in the grid.

**Bug Report Checklist**

- [x] I have granted camera/microphone access permissions while testing
- [x] This bug is reproducible on https://peercalls.com
- [ ] This bug is reproducible on https://peercalls.com/alpha 
\^ /alpha returns 502, can't confirm

**Steps To Reproduce**

1. in Firefox, Share Screen via the button in toolbar
2. stop sharing screen by Firefox native popup bar with "Stop Sharing" button 

**Expected behavior**
- desktop stream is properly removed from all peers

**Desktop (please complete the following information):**
 - OS:      MacOS 11.2
 - Browser  Firefox
 - Version  85

**Additional context**
I dig in a little, and so far the only place in which I managed to trigger any event for this case is [here inside handleLocalMediaStream](https://github.com/peer-calls/peer-calls/blob/f17f526fcd64a52303361bcd6b4033d7f8e78755/src/client/reducers/peers.ts#L65) by adding `track.onended`. My quickfix looks like this:

```diff
    const localStream = localStreams[streamType]
    localStream && localStream.getTracks().forEach(track => {
      removeTrackFromPeer(peer, track, localStream)
    })
    const stream = action.payload.stream

+    stream.getTracks().forEach(track => {
+      if (streamType === 'desktop') {
+        track.onended = function () {
+          removeTrackFromPeer(peer, track, stream)
+        }
+      }

      debug(
        'Add track to peer, id: %s, kind: %s, label: %s',
        track.id, track.kind, track.label,
      )
```

**Comment by jeremija** [comment]
Hi @yedpodtrzitko, thanks for the bug report and for finding a way to fix it. Sorry for replying late - I've been swamped with work lately.

I'll try to take a look at this over the weekend.

**Comment by yedpodtrzitko** [comment]
relevant SO question: https://stackoverflow.com/questions/55953038/why-is-the-ended-event-not-firing-for-this-mediastreamtrack

**Comment by jeremija** [comment]
Hey I took a look at this a few days ago and I was unable to reproduce it. 

Then I remembered that there was already a similar issue #166 that I fixed, but I never tagged the release version until v4.1.0 beta.

Could you verify this is still an issue in latest master?

**Comment by yedpodtrzitko** [comment]
Yes it seems to be fixed. There's a small thing remaining - the Share button stays in the active state as if the screen is still shared.
