### ISSUE TITLE
npm run build:go:linux crashes

### ISSUE THREAD

**Issue by alainvanderbroeck** [peer-calls/peer-calls#197]
v4.1.0-beta1 + v4.1.0-beta2

npm run build:go:linux does not work, it crashes

We are using an Intel processor.

Crash report:
> peer-calls@4.0.0-alpha.0 build:go:linux /home/comvay/test.meetupps.com/public_html
> make pack-linux

fatal: Not a git repository (or any of the parent directories): .git
GOOS=linux GOARCH=amd64 packr build -ldflags "-X main.gitDescribe=" -o peer-calls
/bin/sh: 1: packr: not found
Makefile:18: recipe for target 'pack-linux' failed
make: *** [pack-linux] Error 127
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! peer-calls@4.0.0-alpha.0 build:go:linux: `make pack-linux`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the peer-calls@4.0.0-alpha.0 build:go:linux script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/comvay/.npm/_logs/2021-04-06T10_12_17_341Z-debug.log

**Comment by jeremija** [comment]
Hey, sorry about that. You'll need to install [`packr`](https://github.com/gobuffalo/packr) before you can use that script:

```console
go get -u github.com/gobuffalo/packr/packr
```

You can also download prebuilt binaries [here](https://github.com/peer-calls/peer-calls/releases/tag/v4.1.0-beta3)

**Comment by jeremija** [comment]
Version `4.1.0-beta4` no longer depends on `packr` and uses the [`embed`](https://golang.org/pkg/embed/) package from Go stdlib to embed files in to a binary.

I'm going to close this issue now - feel free to reopen if you're still having trouble with the build!
