### ISSUE TITLE
 browser is not supported

### ISSUE THREAD

**Issue by alainvanderbroeck** [peer-calls/peer-calls#198]
v4.1.0-beta1 + v4.1.0-beta2

It keeps saying that my browser is not supported in alle browsers.
All my browsers are up to date.

**Comment by jeremija** [comment]
Hmm probably some browser functionality detection is failing. Mind sharing the browser details you're experiencing this on?

If you enable debug by going into developer tools and type `localStorage.debug = 'peercalls'` and refersh the page it should show you which features are supported:

![image](https://user-images.githubusercontent.com/1489493/113757284-b95cbc00-9712-11eb-92dc-91b20bf188ee.png)
