### ISSUE TITLE
No connection over mobile Network

### ISSUE THREAD

**Issue by Schnabeldubibu** [peer-calls/peer-calls#210]
HI. my english is not the best also with google translated.

I run Peercalls as an app on my Qnap. Also works very well so far, but no connection is established on the mobile phone via the mobile network. I wifi it works. Does anyone have any tips.?

Best regards
Schnabeldubibu

**Comment by yedpodtrzitko** [comment]
mobile phones dont have public IP, so it's most likely NAT issue. You need to set up a TURN server.

**Comment by Schnabeldubibu** [comment]
Many Thanks. But I think that is beyond my competence. I have no plan how I could do that :) I also think that my QNAP and my bandwidth are not enough for it.
