### ISSUE TITLE
npm run start:watch live reload no longer works

### ISSUE THREAD

**Issue by dennisverspuij** [peer-calls/peer-calls#214]
Hello,

It seems since moving over from packr to go embed the server started from npm start:watch command only serves js/css already present in the build folder prior to the start:server invocation, ignoring any rebuilds from the js:watch or css:watch commands. For quicker dev cycles it would be nice if the go server would continue to pickup and serve changed files, otherwise npm start is now the only way to build then start.

Thanks, greetings,

Dennis

**Comment by jeremija** [comment]
Can you try setting the `PEERCALLS_FS=.` environment variable, for example:

```
PEERCALLS_FS=. npm run ...
```

**Comment by jeremija** [comment]
> can't find any usage in source code either.

That's probably because the `PEERCALLS_` is added as a prefix, so you should search for `"FS"` instead:

```
$ rg '"FS"'
server/configread.go
72:     setEnvString(&c.FS, prefix+"FS")
```

This works for me:

```shell
PEERCALLS_FS=. npm run start:watch
```

Could you double check which revision are you on if the above command doesn't work for you?

**Comment by dennisverspuij** [comment]
Hi, my mistake changes weren't detected in a mount on virtual os, I can confirm the PEERCALLS_FS=. variable does indeed fix live reloads.
Per haps its better to prefix the start:watch chastifol call with it, instead of start:server, for prod launches live reloads may not be desired.
Thanks!

**Comment by jeremija** [comment]
I see your point, but I'd expect the users to build the binary once, and just run the binary in production, there should be no need to use the `npm` scripts anywhere else except in development. Or am I missing something here?

**Comment by dennisverspuij** [comment]
You're right, thanks for the fix.
