### ISSUE TITLE
Origin is getting denied when I host server and client on seperate domain 

### ISSUE THREAD

**Issue by Karthikdb** [peer-calls/peer-calls#224]
I have Hosted golang server and Client server on two different server , On golang server the origin is getting denied when a client tries to connect

Kindly let me know How should I overcome this issue 

Thanks

**Comment by jeremija** [comment]
Is this the same as #226?

**Comment by Karthikdb** [comment]
Thank you @jeremija I have resolved it

**Comment by Karthikdb** [comment]
@jeremija And one more thing how did u overcome session overriding on this system

**Comment by Karthikdb** [comment]
On webrtc calls between two browsers


 where host side calls 
getUserMedia({"audio": true, "video": false}, ...),


 while the guest side calls 
getUserMedia({"audio": true, "video": true}, ...).


The guest will receive only host's audio and but guest can't get videos of their co-guests and 
Host cant receive videos of any guests 



This scenario is common on webrtc but peer calls have used some sort of logic to overcome this. 

I just want to know how?? 

🙇‍♂️

**Comment by Karthikdb** [comment]
> @jeremija And one more thing how did u overcome session overriding on this system

On webrtc calls between two browsers


 where host side calls 
getUserMedia({"audio": true, "video": false}, ...),


 while the guest side calls 
getUserMedia({"audio": true, "video": true}, ...).


The guest will receive only host's audio and but guest can't get videos of their co-guests and 
Host cant receive videos of any guests 



This scenario is common on webrtc but peer calls have used some sort of logic to overcome this. 

I just want to know how?? 

🙇‍♂️

**Comment by jeremija** [comment]
In the old versions I think it was sufficient to set `offerToReceiveVideo` and/or `offerToReceiveAudio` options, but these are now marked as legacy options.

I don't know a lot about your details, but you most likely need to create the transceivers in advance before connecting, or renegotiate after connecting.

For example:

```js
const pc = new RTCPeerConnection()

pc.addTransceiver('video')
pc.addTransceiver('audio')

const offer = await pc.createOffer()
// negotiate...
```

**Comment by Karthikdb** [comment]
That's cool Thank You @jeremija
