### ISSUE TITLE
Can't connect to server from another port

### ISSUE THREAD

**Issue by Karthikdb** [peer-calls/peer-calls#226]
**Describe the bug**

**Bug Report Checklist**

- [ ] I havexample:anted camera/microphone access permissions while testing
- [ ] This bug is reproducible on https://peercalls.com
- [ ] This bug is reproducible on https://peercalls.com/alpha

**Steps To Reproduce**

1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS:      
 - Browser  
 - Version  

**Smartphone (please complete the following information):**
 - Device:  
 - OS:      
 - Browser: 
 - Version: 

**Additional context**

I am trying to connect websocket server from another port but this error

Create websocket context: failed to accept WebSocket connection: request Origin "http://localhost:30C:/Users/KARTHIK/Documents/peer-calls/server/wssub.go:90: accept websocket connection

**Comment by jeremija** [comment]
Hmm I don't think we're currently checking the `Origin` header. Is this application running behind a reverse proxy?
