### ISSUE TITLE
Rotate image

### ISSUE THREAD

**Issue by jjsarton** [peer-calls/peer-calls#227]
**Describe the feature**

On a Smartphone with Google-Chrome and or Firefox, it shall be goodto take account of the device rotation and set the orientation of the video accordingly.

**Comment by jeremija** [comment]
Hi @jjsarton if you have device rotation enabled, the browser should handle the rotation for you. Is this not working for you?

**Comment by jjsarton** [comment]
Hi@jeremija,
The device rotation is enabled on the smartphone. The picture from the smartphone camera is rotated on the smartphone itself but not the picture from the PC which  is an other member for the chat. See attached file.
![rotation](https://user-images.githubusercontent.com/951168/121468602-5cec7600-c9bb-11eb-84fa-ce4981c4af22.png)

**Comment by jeremija** [comment]
I don't think I can reproduce the issue you are describing here. See the below screenshots (tested on the latest version of Firefox for Android and Firefox on Mac). All of the screenshots below were taken in the same call, with the mobile device rotated by 90 degrees during the call.


![screenshot1](https://user-images.githubusercontent.com/1489493/121482868-d55c3280-c9cd-11eb-9e8e-b4bd96240b93.png)
![screenshot2](https://user-images.githubusercontent.com/1489493/121482940-eb69f300-c9cd-11eb-9bc5-d9eba1300297.png)
![screenshot3](https://user-images.githubusercontent.com/1489493/121482893-dc834080-c9cd-11eb-93b9-326641177c90.png)
![screenshot4](https://user-images.githubusercontent.com/1489493/121482895-ddb46d80-c9cd-11eb-8362-00cc6fb1aff0.png)

**Comment by jjsarton** [comment]
Sorry for my mistake. I have checked this again, the automatic rotation mode what not set. After correction this work  well.
