### ISSUE TITLE
Choose media on firefox

### ISSUE THREAD

**Issue by jjsarton** [peer-calls/peer-calls#228]
**Describe the bug**

On Firefox the used media is always the first media shown from the device enumeration. 
I have 2 camera and selecting which is to be used don't work.

**Bug Report Checklist**

- [x ] I havexample:anted camera/microphone access permissions while testing
- [ x] This bug is reproducible on https://peercalls.com
- [ ] This bug is reproducible on https://peercalls.com/alpha

**Steps To Reproduce**
Attach 2 camera to the computer, try to select the second camera with Firefox

1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS:       Linux
 - Browser   Firefox
 - Version  88

**Smartphone (please complete the following information):**
 - Device:  
 - OS:      
 - Browser: 
 - Version: 

**Additional context**

See also Code sample on the following URL:
https://github.com/webrtc/samples/blob/gh-pages/src/content/devices/input-output/js/main.js
The constraint for  getUserMedia() shall include exact.

**Comment by jeremija** [comment]
Thanks for reporting! Looks like this is a bug indeed, something must've happened on the recent refactoring or the browsers started acting differently.

**Comment by jeremija** [comment]
@jjsarton Can please check if the fix above works for you?

**Comment by jjsarton** [comment]
I have tested the changes, I am able to select the first or second camera before joining the room. Within the room I can't change the camera.
