### ISSUE TITLE
Could you add password access?

### ISSUE THREAD

**Issue by eXqusic** [peer-calls/peer-calls#23]
Could you add password access so that you need to input a password to actually join the site? I use this with my girlfriend and would like to be able to only allow her to join it.

**Comment by jeremija** [comment]
Hey, thanks for the comment! Yes, that's on my todo list. That and adding a "join" button, instead of joining the call immediately after opening the link. Have you noticed any issues with connectivity?

**Comment by seiterseiter** [comment]
Nope its perfect! My girlfriend did say that its annoying how the video is reversed haha but it doesnt really matter

**Comment by lil5** [comment]
If you run a server yourself you could use a reverseproxy with auth 
- nginx https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/
- apache2 https://httpd.apache.org/docs/2.4/howto/auth.html

**Comment by jeremija** [comment]
Closing this issue in favor of #141, which should add password access once it is implemented.
