### ISSUE TITLE
Backend moderator.

### ISSUE THREAD

**Issue by supertiger1234** [peer-calls/peer-calls#232]
I'm working on a chat app like discord and I would like to implement group voice calling. Would this lib be suitable? 

Is there a way to kick users from the call using my backend server?
Does it support group calling?
Does SFU topology hide peoples IPs from getting exposed?

I don't have much experience with webrtc and voice calling

Thanks

**Comment by jeremija** [comment]
Hey, Peer Calls is more like a "product" than a library, though you're welcome to use it as you see fit. The library it uses is [pion/webrtc](https://github.com/pion/webrtc).

> Is there a way to kick users from the call using my backend server?
Currently there is no way to do it, other than manually banning the IP from connecting to you server. 

> Does it support group calling?
Yes, as you can see on https://peercalls.com

> Does SFU topology hide peoples IPs from getting exposed?
Yes, although the server will stlil see the users' real IPs.

**Comment by supertiger1234** [comment]
Ah thanks a lot, I'll see what I can do.
