### ISSUE TITLE
Do not set default ICE servers by default

### ISSUE THREAD

**Issue by jeremija** [peer-calls/peer-calls#234]

**Comment by prologic** [comment]
@jeremija Just wondering if you could give a short explanation (_like I'm 5_) of ICE/STUN servers and how they're used within Peer Calls?

As I mentioned before, I have my Peer Calls instance working very nicely (See #236) which is sitting on one of my Swarm nodes in a Docker Swarm cluster behind Traefik as the L7/ingress load balancer. Nothing too fancy.

After playing with this and having lots of successful calls, and reading about TURN, STUN and ICE w/ WebRTC it's not _actually_ super clear to me whether I need to bother setting up my own TURN server using say [coturn](https://hub.docker.com/r/coturn/coturn)...

Are the defaults still (_as per the [README](/README.md)):

- stun:stun.l.google.com:19302
- stun:global.stun.twilio.com:3478?transport=udp

Are these just used to establish peer's public IP addresses (IPv4?)

How does IPv6 come into play here?

Sorry for the q's I need to understand this, quite a few folks have said to me "Do you have a TURN server setup too?", "Oh you need a TURN server?" 😂
