### ISSUE TITLE
Feedback: PeerCals is awesome! 😍

### ISSUE THREAD

**Issue by prologic** [peer-calls/peer-calls#236]
Hello All 👋

I just wanted to drop by and say that I absolutely love ❤️ this project! Not only is most of it written in Go using a library I'm very familiar with (_but never had the time to play with myself_), but this just works™ 😂

I was able to spin up a production instance of Peer Calls in my home infrastructure that runs a Docker Swarm Cluster with a mere 23 lines of YAML: Example (_modify to suite, I use [Traefik](https://traefik.io/) as my ingress_):

```#!yaml
---
version: "3.8"

services:
  peercalls:
    image: peercalls/peercalls:latest
    networks:
      - traefik
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.services.meet_peercalls.loadbalancer.server.port=3000"
        - "traefik.http.routers.meet_peercalls.rule=Host(`meet.mydomain.tld`)"
        - "traefik.http.routers.gitea.priority=2"
      restart_policy:
        condition: on-failure

networks:
  traefik:
    external: true
```

I literally had to do _nothing_ else! I had a few test calls with some colleagues and friends and even on Mobile. This stuff is brilliant!

Keep up the good work (_I may find some time to contribute some of my time or funds to this proejct_)

The most important aspects of this project that tick the boxes for me are:

- [X] It's written in a language I can understand and is portable and not resource hungry (_Java™ **cough**_)
- [X] It's so easy to spin up and get running (_single binary, docker image, very little if not zero configuration_)

👌

**Comment by jeremija** [comment]
Hi @prologic, thanks for your kind words - I was happy to hear you had a nice experience setting it all up. Hope it stays on the same level as you use it more! Feel free to open new issues should you find any bugs or have ideas for improvements!
