### ISSUE TITLE
Default ice servers used

### ISSUE THREAD

**Issue by harikt** [peer-calls/peer-calls#239]
Hi,

I am using the docker container and passing a `config.yml` file as below.

```
ice_servers:
- urls:
  - 'stun:coturn.buildful.com:5349'
- urls:
  - 'stun:coturn2.buildful.com:5349'
```

In the `/call` url the `index.js` was having 

```
p.config={iceServers:[{urls:["stun:stun.l.google.com:19302","stun:global.stun.twilio.com:3478"]}],
```

Is this related to https://github.com/peer-calls/peer-calls/issues/234 and https://github.com/peer-calls/peer-calls/pull/235 ?

**Steps To Reproduce**

1. docker run -d --rm -it -p 3000:3000 peercalls/peercalls:latest -v /path/config.yml:/peer-calls/config.yml peer-calls -c /peer-calls/config.yml
2. Load the url and check in `/static/index.js`

**Expected behavior**
Expecting the `iceServers:[{urls:["stun:coturn.buildful.com:5349", "stun:coturn2.buildful.com:5349"]}` as the one passed.

**Comment by jeremija** [comment]
Hi @harikt, I believe you should set the volume paths before specifying the image name. I also think you need to omit `peer-calls` from the `docker run`  command because it is already defined as an entry point in the `Dockerfile`.

Can you try running it like this and see if it works?

```
docker run --rm -it -v /path/config.yml:/peer-calls/config.yml -p 3000:3000 peercalls/peercalls:latest -c /peer-calls/config.yml
```

I think the parsed config should be printed as one of the first log statements.

**Comment by harikt** [comment]
Thank you @jeremija ,

I did some test running the container as you suggested. This is the log information.

```
2021-08-13T06:26:28.489603Z  info [                main] Using config: {BaseURL: BindHost: BindPort:3000 FS: ICEServers:[{URLs:[stun:coturn.buildful.com:5349] AuthType: AuthSecret:{Username: Secret:}} {URLs:[stun:coturn2.buildful.com:5349] AuthType: AuthSecret:{Username: Secret:}} {URLs:[turn:coturn.buildful.com:5349] AuthType:secret AuthSecret:{Username:username Secret:password}}] TLS:{Cert: Key:} Store:{Type:memory Redis:{Host: Port:0 Prefix:}} Network:{Type:mesh SFU:{Interfaces:[] JitterBuffer:false Protocols:[] TCPBindAddr: TCPListenPort:0 Transport:{ListenAddr: Nodes:[]} UDP:{PortMin:0 PortMax:0}}} Prometheus:{AccessToken:}}
```

This is the config.yml file.

```
ice_servers:
- urls:
  - 'stun:coturn.buildful.com:5349'
- urls:
  - 'stun:coturn2.buildful.com:5349'
- urls:
  - 'turn:coturn.buildful.com:5349'
  auth_type: secret
  auth_secret:
    username: "username"
    secret: "password"
```

But when I check the https://call.rxdb.com/static/index.js it still shows the google, twilio stun server.

```
p.config={iceServers:[{urls:["stun:stun.l.google.com:19302","stun:global.stun.twilio.com:3478"]}],
```

**Comment by jeremija** [comment]
These are the defaults used by `simple-peer`, but they shouldn't be used. You should see the configuration being passed through `index.html`, and if you go to `about:webrtc` in Firefox it should tell you which ICE servers were used.

**Comment by harikt** [comment]
Thank you @jeremija. I checked the chrome://webrtc-internals and noticed it was using correct stun / turn servers.

Thank you.
