### ISSUE TITLE
Share button to send link via email/sms/twitter/etc

### ISSUE THREAD

**Issue by trivett** [peer-calls/peer-calls#24]
Hello all. Just discovered this project. My first impulse after I tried it out was to look for a place to share the room with someone else. 

Please +1 if you like that idea and I will start working on it!

**Comment by jeremija** [comment]
Hey @trivett - thank you for your interest! Right now you can share it by just copying the link to clipboard, but feel free to add the buttons!

The one thing I'd ask is to also write unit tests for the new functionality if there will be any logic involved.

**Comment by moosh3** [comment]
I am looking to implement this exact functionality. Supporting an interface that defines a generic `Notifier` could allow sending notifications via email, SMS, etc.

**Comment by jeremija** [comment]
The `Copy the clipboard` button is already there on desktop, and it switches to `Share` button on mobile browsers that support this functionality. I'm closing this in favor of #10.
