### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by dennisverspuij** [peer-calls/peer-calls#254]
Hello, somehow with latest master version I do not seem to get out any logging from the peercalls server other than the initial lines below, even when I set and export PEERCALLS_LOG="*":

> info [                main] Using config: {BaseURL: BindHost:127.0.0.1 BindPort:3000 .......}
> info [                main] Listen local_addr=127.0.0.1:3000

Any idea what may be causing this?

Thanks for any help.

**Comment by jeremija** [comment]
There was a change in the logging package, can you try using `**` instead of `*`?

**Comment by dennisverspuij** [comment]
Hi, thanks that helps indeed, I get room, connection and signals logged. However, since the README example mentions -sdp and pion:* stuff I was expecting more, is there a way to have sdp's logged server-side, sdp:debug does not seem to do anything?

Btw I see a growing namespace ...et_handler:mesh:mesh:mesh:mesh:mesh..... for the Send signal logging, seems a small glitch there.

**Comment by jeremija** [comment]
> Btw I see a growing namespace 

Thanks for the report, here's a fix for that: https://github.com/peer-calls/peer-calls/pull/255

The logs you're looking for should be under `**:signaller:trace`, see [server/wrtcsignaller.go](server/wrtcsignaller.go) for more info.

However, these are only relevant to SFU network mode, looks like we don't log the signals for Mesh mode. You should be able to enable debug logging in dev console to log signals (`localStorage.debug = 'peercalls:sdp'`) and refresh the page.

**Comment by dennisverspuij** [comment]
Thanks for the fix and pointing me in right direction. I added logging of mesh signal payloads with simple addition:
```
--- a/server/mesh.go	
+++ b/server/mesh.go	
@@ -75,6 +75,9 @@
 				log.Info("Send signal to", logger.Ctx{
 					"target_client_id": targetClientID,
 				})
+				log.Trace("Payload", logger.Ctx{
+					"payload": signal.Signal,
+				})
 				err = adapter.Emit(targetClientID, message.NewSignal(roomID, message.UserSignal{
 					Signal: signal.Signal,
 					PeerID: clientID,
```
