### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by GRASBOCK** [peer-calls/peer-calls#272]
**Describe the bug**

I cannot open the site. 
> 504 Gateway Time-out
> nginx
> 

**Bug Report Checklist**

- ~~[ ] I havexample:anted camera/microphone access permissions while testing~~
- [x ] This bug is reproducible on https://peercalls.com
- [x ] This bug is reproducible on https://peercalls.com/alpha
Gateway Time-out
**Steps To Reproduce**

1. Go to[]( https://peercalls.com/alpha)
2. See error
> 504 Gateway Time-out
> nginx
> 

**Expected behavior**
The create room page

**Desktop (please complete the following information):**
 - OS: Xubuntu
 - Browser firefox
 - Version 103

**Comment by jeremija** [comment]
Thanks for the feedback. It should be fixed now. I need to improve my alerts...

**Comment by GRASBOCK** [comment]
Yep, thanks for the quick fix :)
