### ISSUE TITLE
 Failed at the peer-calls@4.0.0 start:server script 'PEERCALLS_FS=. go run main.go'.

### ISSUE THREAD

**Issue by satyashetty** [peer-calls/peer-calls#286]
**Describe the bug**
when initiating npm start getting the following error
 Darwin 22.6.0
npm ERR! argv "/Users/satyashetty/.nvm/versions/node/v16.17.0/bin/node" "/Users/satyashetty/node_modules/.bin/npm" "run" "start:server"
npm ERR! node v16.17.0
npm ERR! npm  v2.15.12
npm ERR! code ELIFECYCLE
npm ERR! peer-calls@4.0.0 start:server: `PEERCALLS_FS=. go run main.go`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the peer-calls@4.0.0 start:server script 'PEERCALLS_FS=. go run main.go'.
npm ERR! This is most likely a problem with the peer-calls package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     PEERCALLS_FS=. go run main.go
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs peer-calls
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls peer-calls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Steps To Reproduce**

compiling to start the application

**Expected behavior**
run the application

**Comment by jeremija** [comment]
What's the output of `PEERCALLS_FS=. go run main.go`? Do you have Go installed?

**Comment by satyashetty** [comment]
I managed to get through this error by restarting visual studio.  but there
is another issue  that I am facing when I am trying to test the application
locally, When I do a test through Firefox and Safari I am able to add
multiple instances. But in Chrome the instance I am not able to. attaching
a screenshot for reference.

on chrome, i get the following message

Peer connection close

*and on safari i get the message that its connecting to the peer endlessly*

**Comment by jeremija** [comment]
The README.MD in the repo has configuration instructions. I'm not able to provide installation support via GitHub due to the nuances of different WebRTC browser implementations, configuration options, hosting providers and firewall setups. You might also need to run a TURN/STUN server. If you're able to reproduce the issue on peercalls.com I look into it.

**Comment by satyashetty** [comment]
Thank you for your reply. I will try your suggestions

Regards
Satya
