### ISSUE TITLE
Switch to back cam in Mobile

### ISSUE THREAD

**Issue by mQckingbird** [peer-calls/peer-calls#30]
My phone has two cameras.
One in the front, and other in the back; nothing crazy.

Though, I'd like to switch between the front camera to the back camera with just a button.
Is this possible?

**Comment by jeremija** [comment]
IIRC firefox mobile lets you choose which camera to use. You'd need to use `mediaDevices.enumerateDevices` to get a list of cameras and then provide a way to change the stream. The library that's used for establishing the peer connection did not support dynamic switching of streams, meaning the user would have to reconnect (or refresh the page). I don't currently have the time to implement that but you're welcome to implement it and create a pull request. Check the CONTRIBUTING.md file if you're interested.

**Comment by matikbird** [comment]
I'll checked and tried but nothing came up just yet 👎

**Comment by matikbird** [comment]
By the way, in which files do you have the camera settings and all that so I can look further?

Help me out with that so I can contribute, I'm short in time as well, but I'll do my best

**Comment by matikbird** [comment]
https://github.com/feross/simple-peer/issues/114#issuecomment-269812335

**Comment by matikbird** [comment]
[https://github.com/feross/simple-peer/issues/114#issuecomment-269812335](https://github.com/feross/simple-peer/issues/114#issuecomment-269812335)

We would end-up refreshing everything anyways and load another code just to get this done. That seems pretty rough.

Any ideas, @jeremija?

**Comment by jeremija** [comment]
This should work since 0a40e72 (not in production yet). Users can now select audio and video input source before connecting. I still need to add the ability to show the configuration menu after connecting.

**Comment by jeremija** [comment]
Switching camera dynamically after connecting has been possible since ef55c5c (`v4.0.0`)
