### ISSUE TITLE
Many users room

### ISSUE THREAD

**Issue by yarekc** [peer-calls/peer-calls#37]
is this peer2peer (so limited to 6/8 max) or are the peers relayed ?

**Comment by yarekc** [comment]
well that's a practical number of users since you directly stream to 6-8 users.
Ex: you cannot stream to 1000 users with webrtc directly: you need a SFU server for that. 
suer1<------->SFU server with bandwidth<------->other users

**Comment by jeremija** [comment]
You're right, the bandwidth usage would be too high as the user count grows. I currently have no resources to manage and maintain a SFU server, but it does sounds like a powerful solution (provided that the streams would still be encrypted and not readable from the server-side).

**Comment by jeremija** [comment]
Closing this issue since Peer Calls has a built-in SFU since v4.
