### ISSUE TITLE
Library to implement cliente in VueJs

### ISSUE THREAD

**Issue by alex0195** [peer-calls/peer-calls#87]
Your development is excellent, congratulations, I would like to know if there is a way to work it as with peerjs for cdn, I am trying to do the front with VueJs? Thanks

**Comment by jeremija** [comment]
Thanks for your interest in Peer Calls! I'm not familiar with PeerJS so I'm sure I understand what you'd like to do. Could you please clarify?

**Comment by alex0195** [comment]
Ok, just being able to make the interface script in the client, so that you can have the server only as a backend process and the client in VueJs or pure javascript, peerjs provides a js library that can be implemented with cnd or npm and offers methods to connect example:
Peer = new PeerJs (ID, {server-conf});
Peer ('conex', callback) where conex is activated once connected.

In your readme I see that you have it in a similar way but everything is managed from the server as a single app.

Thanks for your answer

**Comment by jeremija** [comment]
If you want to use the server side, and code your own frontend, check out `src/client/index-simple.tsx` from the `server-go` branch, but use it on the `master` since server-go is an unstable branch at the moment.

**Comment by jeremija** [comment]
Closing this as it's not really an issue. If you have any more questions, please feel free to comment.
