### ISSUE TITLE
Peers don't reloads

### ISSUE THREAD

**Issue by litashg** [peer-calls/peer-calls#94]
Hello, Jerko. 
I found an issue. I have 6 users in 1 room, and they run nicely. But sometimes one of the clients lost peer. One or two video screens just removes. How can I reload peers and add a video track to the user's screens? 
I tried this on peercalls.com

**Comment by jeremija** [comment]
You could try to fix it by emitting a `ready` websocket event after `simple-peer`'s `disconnect` event is fired from the initiator's side. I believe this will be calleed if the websocket reconnects, so you should make sure not to call it twice.

**Comment by ahmetozalp** [comment]
If the page refreshes after matching, it won't reconnect and gives a black screen and a random username.

![GitHub Logo](https://i.hizliresim.com/iB0Tud.png)

**Comment by ahmetozalp** [comment]
yes problem v4 roleback and fix.

**Comment by ahmetozalp** [comment]
@litashg did you solve the problem? the sound of the user with the camera turned off, but no video
