### ISSUE TITLE
there is no vıdeo but there is sound

### ISSUE THREAD

**Issue by ahmetozalp** [peer-calls/peer-calls#95]
Hello, we constantly turn the camera on and off during the video call, I don't know why after a while, but the video camera stays on the black screen, it doesn't improve again, but why does it sound?

turn server: google.

-------

I also see log lines in the codes how do I activate them so I can display them with 'pm2 logs'

**Comment by jeremija** [comment]
Which browser are you using? I cannot reproduce this in latest Firefox locally (two windows connected to same room).

Regarding the logging, see the [README](https://github.com/peer-calls/peer-calls/blob/master/README.md#logging).

**Comment by ahmetozalp** [comment]
maybe chrome.

Do you have any idea why there is no sound?

**Comment by ahmetozalp** [comment]
I have to ask you something from the e-mail. Can you share it with me?

**Comment by jeremija** [comment]
My email is in the commit history.

**Comment by ahmetozalp** [comment]
Have you ever used or heard about kurento?
