### ISSUE TITLE
server-go build instructions

### ISSUE THREAD

**Issue by kubrickfr** [peer-calls/peer-calls#98]
Hello,

I've been watching the progress of development of the server-go implementation and I'm itching to give it a try and potentially contribute.

Would you be kind enough to provide build instructions?

**Comment by jeremija** [comment]
Hi @kubrickfr, thanks for your interest in Peer Calls! Hope this helps:

# Running for development

Go 1.14 and NodeJS 8+ are prerequisites.

```
git clone https://github.com/jeremija/peer-cals
cd peer-calls
git checkout server-go
npm install
```

Run `npm run build` to build javascript and css, or `npm run start:watch` to watch for changes. Then run `npm start` to start the go server.


# Building a binary

To build a runnable binary, use:

```
npm run build
npm run build:go
# or
npm run build:go:linux
```

These last `build:go` commands should work on MacOS or Linux, but the application itself should work on Linux, I just haven't had the time to get rid of the `Makefile`. You also need to have [`packr`](https://github.com/gobuffalo/packr) installed.

# Running the tests

```bash
npm run test
go test ./...
```

# Configuration

You can use a YAML config file, or environment variables to configure your app. You can specify the config file via `-c /path/to/config.yml`. For a full list of config variables, see [config/types.go](https://github.com/peer-calls/peer-calls/blob/server-go/src/server/config/types.go), or [config/read.go](https://github.com/peer-calls/peer-calls/blob/server-go/src/server/config/read.go#L58). All env variables are prefixed by `PEERCALLS_`.

The defaults should be more or less the same as the `master` branch, and connections will be established peer-to-peer.

To test out the new Selective Forwarding Unit, set the `PEERCALLS_NETWORK_TYPE=sfu` variable. However, this is currently buggy and I'm actively contributing to [`pion/webrtc`](https://github.com/pion/webrtc) to make this work correctly in most browsers.

Let me know if you have any more questions or find any issues!

**Comment by jeremija** [comment]
I've updated the [`README.md`](https://github.com/peer-calls/peer-calls/blob/server-go/README.md) on the `server-go` branch with all the necessary instructions, as well as the `Dockerfile`. The latest `alpha` tag is built automatically from this branch:

```
docker run --rm -p 3000:3000 peercalls/peercalls:alpha
```

Feel free to reopen if you have any more questions!

**Comment by kubrickfr** [comment]
Perfect! Thank you, I'll give it a shot.
