### ISSUE TITLE
JWT

### ISSUE THREAD

**Issue by michelmelo** [peer-calls/peer-calls#99]
hello how can we add jwt?

**Comment by jeremija** [comment]
Hi @michelmelo, there are currently no plans to support any sort of authentication. Some people have had success by configuring a reverse proxy to [use basic authentication and then automatically set the nickname via `X-Forwarded-User` header](https://github.com/peer-calls/peer-calls/issues/77#issuecomment-602866489).

**Comment by michelmelo** [comment]
I ask why yesterday I have the WS I need to send a token

ok it's basically something like this

this.socket = io("localhost:5000", {
      extraHeaders: {
        Authorization: "My Bearer authorization_token_here"
      }
    });

**Comment by jeremija** [comment]
Hi @michelmelo, the `extraHeaders` property only works for `polling` transport, and not for `websocket` transport.

However, you should be able to access the cookie header on the server-side. See [`namespace.use`](https://socket.io/docs/server-api/#namespace-use-fn):

```javascript
io.use((socket, next) => {
  if (socket.request.headers.cookie) return next();
  next(new Error('Authentication error'));
});
```
